/**
 * SchemaPulse 前端工作台编排层
 * 领域状态与逻辑拆分于 composables/ 目录 (模块级单例状态):
 *   core      导航 / 共享数据仓库 / 刷新编排 / 样式工具
 *   targets   旧版平铺监控目标与大盘目标统计
 *   env       环境管理域
 *   machines  机器管理域 (含机器级环境变量池)
 *   apis      接口管理域 (Postman 风格调参 / 前后置操作 / 即时调试)
 *   postman   Postman 数据导入域
 *   lab       Schema 契约实验室
 * 模块间存在安全的 ESM 循环引用 (均仅在函数体内惰性调用)
 */
import { onMounted } from 'vue'
import axios from 'axios'
import { activeMenuKey, apiList, avgTcpLatency, currentNav, dashboardEnvironments, environmentList, fetchData, filterBySidebarGroup, formatLatency, formatTime, getGroupColor, getGroupTagType, getLatencyBadgeClass, getStatusBadgeClass, getStatusIcon, groupList, handleManualRefresh, handleMenuSelect, lastRefreshTime, loading, machineList, navTitle, offlineMachineCount, onlineMachineCount, openDocs, summary, switchNav, targets } from './composables/core'
import { activeTarget, createDialogVisible, downTargets, drawerVisible, echartsInstance, editingTargetId, filteredDownTargets, filteredTargets, form, handleDelete, handleInferSchema, handleTrigger, historyList, incidentSearchQuery, inferring, loadingHistory, openCreateDialog, openEditDialog, openMetricsDrawer, renderChart, sampleJsonText, selectedGroup, submitCreateTarget, submitting, triggeringId } from './composables/targets'
import { editingEnvId, envDialogVisible, envForm, envSearchQuery, envSubmitting, filteredEnvironments, getEnvBorderTopColor, getEnvMachineCount, getEnvStatusBadgeClass, getEnvTargetCount, goToEnvApis, goToEnvMachines, goToEnvTargets, handleDeleteEnv, openCreateEnvDialog, openEditEnvDialog, submitEnvForm } from './composables/env'
import { addEnvVarRow, copyEnvVarRef, copyFallback, currentEnvMachines, currentEnvMachinesForKpi, currentMachineEnvironment, editingMachineId, envVariablesList, envVariablesSaving, envVarsDialogVisible, fetchMachineEnvironment, filteredMachines, getMachineApiCount, getVarRef, goToMachineTargets, handleDeleteMachine, handleTriggerMachine, machineDialogVisible, machineEnvAvgTcpLatency, machineEnvOfflineCount, machineEnvOnlineCount, machineEnvTotalCount, machineForm, machineSearchQuery, machineSubmitting, onPathInput, openCreateMachineDialog, openEditMachineDialog, openEnvDialog, removeEnvVarRow, resetBaseUrlToMachine, saveEnvVariables, selectedMachineBaseUrl, selectedMachineDisplayName, selectedMachineEnv, selectedMachineHost, submitMachineForm, triggeringMachineId } from './composables/machines'
import { activeDefaultHeadersCount, addHeaderRow, addParamRow, addPostActionRow, addPreActionRow, apiActiveTab, apiAuthConfig, apiAuthType, apiBodyText, apiBodyType, apiDialogVisible, apiEnvAvgLatency, apiEnvHealthyCount, apiEnvIssueCount, apiEnvOnlineMachineCount, apiEnvTotalCount, apiForm, apiHeadersList, apiInferring, apiIntervalUnit, apiIntervalValue, apiParamsList, apiPostActionsList, apiPreActionsList, apiResponseTab, apiSampleJson, apiSearchQuery, apiSubmitting, apiTestResult, apiTestRunning, applyPostActionPreset, applyPreActionPreset, avgApiLatency, clearBodyJson, copyResponseBody, copyText, createDefaultHeaders, currentEnvApisForKpi, currentEnvMachineOptions, editingApiId, filteredApis, formatBodyJson, formatIfJson, formatIntervalDisplay, formatSampleJson, formatSchemaJson, getEffectiveHeaders, getIntervalTooltip, handleDeleteApi, handleInferApiSchema, handleTestRunApi, handleTriggerApi, healthyApiCount, inferSchemaFromTestResult, insertMacroToBody, isHeaderOverridden, isSyncingUrlParams, issueApiCount, minifyBodyJson, onPostActionTypeChange, openApiMetricsDrawer, openCreateApiDialog, openEditApiDialog, removeHeaderRow, removeParamRow, removePostActionRow, removePreActionRow, safeFormatJson, safeMinifyJson, selectedApiEnv, selectedApiMachine, selectedApiStatus, setQuickInterval, showDefaultHeaders, submitApiForm, syncParamsToPath, syncPathToParams, systemDefaultHeaders, toggleApiActive, triggeringApiId, selectedApiRows, apiTableRef, isBatchOperating, handleApiSelectionChange, clearApiSelection, handleBatchDeleteApis, handleBatchToggleActive, handleBatchSetInterval, apiCurrentPage, apiPageSize, paginatedApis } from './composables/apis'
import { executeConfirmPostmanImport, goToImportedApisView, handlePostmanFileChange, handlePostmanTextParse, isPostmanApiSelected, onPostmanImportMachineChange, openGenericPostmanImport, openPostmanImportForMachine, postmanConflictPolicy, postmanCronInterval, postmanImportActiveTab, postmanImportDialogVisible, postmanImportLoading, postmanImportMachine, postmanImportMachineId, postmanImportSuccessResult, postmanPreviewData, postmanRawJsonText, postmanSelectedApis, postmanSyncEnvVars, postmanUpdateBaseUrl, resetPostmanImport, togglePostmanApiSelection, toggleSelectAllPostmanApis } from './composables/postman'
import { copyLabSchema, copySchemaToValidate, handleLabInfer, handleLabValidate, labActiveTab, labInferring, labJsonInput, labSchemaOutput, labStrictMode, labValidateJsonText, labValidateSchemaText, labValidating, labValidationResult, loadValidateSample } from './composables/lab'
import { activeScenarioDefaultHeadersCount, activeStep, activeStepIndex, addScenarioStep, insertScenarioStep, moveScenarioStep, moveStepLeft, moveStepRight, cloneScenarioStep, addStepHeaderRow, addStepParamRow, addStepPostActionRow, addStepPreActionRow, apiImportDialogVisible, apiImportMethodFilter, apiImportSearch, apiImportSelection, apiImportTableRef, apiImportOrderedList, apiImportInsertPosition, moveImportedApiUp, moveImportedApiDown, removeImportedApi, clearAllImportedApis, applyStepPostActionPreset, applyStepPreActionPreset, clearStepBodyJson, confirmImportApisAsSteps, fetchScenarios, fillActiveStepFromApi, filteredScenarios, formatStepBodyJson, getMethodBadgeStyle, getScenarioStatusBadgeClass, getScenarioStatusText, handleApiImportSelectionChange, handleDeleteScenario, importableApis, isStepHeaderOverridden, minifyStepBodyJson, onStepPathInput, onStepPostActionTypeChange, openApiImportDialog, openCreateScenarioDialog, openEditScenarioDialog, removeScenarioStep, removeStepHeaderRow, removeStepParamRow, removeStepPostActionRow, removeStepPreActionRow, resetScenarioBaseUrlToMachine, scenarioActiveCount, scenarioCleanupCount, scenarioDialogVisible, editingScenarioId, scenarioForm, scenarioIntervalUnit, scenarioIntervalValue, scenarioList, scenarioLoading, scenarioMachineDisplayName, scenarioMachineOptions, scenarioSearchQuery, scenarioStepTotalCount, scenarioSteps, scenarioSubmitting, scenarioSystemDefaultHeaders, scenarioTotalCount, selectScenarioStep, selectedScenarioEnv, selectedScenarioMachine, selectedScenarioStatus, toggleScenarioActive, setQuickScenarioInterval, showStepDefaultHeaders, stepActiveTab, submitScenarioForm, scenarioRunningId, scenarioResultVisible, scenarioResult, stepTestRunning, stepTestResult, handleRunScenario, getStepResultBadge, handleTestRunStep, stepSchemaSampleJson, stepInferring, formatStepSchemaJson, inferStepSchemaFromSample, inferStepSchemaFromTestResult, scenarioMetricsDrawerVisible, scenarioMetricsLoading, activeScenarioMetrics, scenarioHistoryList, openScenarioMetricsDrawer, expandedScenarioStepIds, isScenarioStepsExpanded, toggleScenarioStepsExpand, isAllScenarioStepsExpanded, toggleAllScenarioStepsExpand, scenarioVariablesList, scenarioVariablesDrawerVisible, scenarioVariablesCount, addScenarioVariableRow, removeScenarioVariableRow, clearScenarioVariables, getScenarioVariablesObject, setScenarioVariablesFromObject, copyVariableMacro, stepResponseTab, stepExtractedVarNames, customExtractPath, customExtractVarName, customExtractPreview, stepExtractableFields, getStepResponseFormattedBody, isFieldExtractedInActiveStep, quickExtractFieldToScenarioVariable, addCustomExtractToScenarioVariable, insertScenarioVarToStepBody, insertScenarioVarToStepParam, insertScenarioVarToStepHeader, insertScenarioVarToStepPath, selectedScenarioRows, scenarioTableRef, isScenarioBatchOperating, handleScenarioSelectionChange, clearScenarioSelection, handleBatchDeleteScenarios, handleBatchToggleScenarioActive, handleBatchSetScenarioInterval, scenarioCurrentPage, scenarioPageSize, paginatedScenarios } from './composables/scenarios'

// 配置 Axios 默认基础 API 路由 (开发环境走 Vite 代理, 生产可用 VITE_API_BASE_URL 指定)
axios.defaults.baseURL = import.meta.env.VITE_API_BASE_URL || ''

// 全局请求拦截与错误兜底
axios.interceptors.response.use(
    response => response,
    error => {
        if (error.code === "ERR_NETWORK" || !error.response) {
            console.error("[SchemaPulse API Network Error]", error);
        }
        return Promise.reject(error);
    }
);

export function workbenchSetup() {
    onMounted(() => {
        fetchData();
        fetchScenarios();
        setInterval(fetchData, 15000);
        setInterval(fetchScenarios, 15000);
        window.addEventListener("resize", () => {
            if (echartsInstance) echartsInstance.resize();
        });
    });

        const setupResult = {
            loading,
            targets,
            groupList,
            selectedGroup,
            currentNav,
            activeMenuKey,
            handleMenuSelect,
            navTitle,
            downTargets,
            incidentSearchQuery,
            filteredDownTargets,
            filteredTargets,
            switchNav,
            filterBySidebarGroup,
            getGroupColor,
            getGroupTagType,
            getStatusBadgeClass,
            getStatusIcon,
            summary,
            triggeringId,
            createDialogVisible,
            submitting,
            inferring,
            sampleJsonText,
            form,
            labActiveTab,
            labJsonInput,
            labStrictMode,
            labSchemaOutput,
            labInferring,
            handleLabInfer,
            copyLabSchema,
            copySchemaToValidate,
            labValidateSchemaText,
            labValidateJsonText,
            labValidating,
            labValidationResult,
            loadValidateSample,
            handleLabValidate,
            drawerVisible,
            activeTarget,
            loadingHistory,
            historyList,
            fetchData,
            lastRefreshTime,
            handleManualRefresh,
            handleTrigger,
            handleDelete,
            openCreateDialog,
            openEditDialog,
            editingTargetId,
            handleInferSchema,
            submitCreateTarget,
            openMetricsDrawer,
            formatTime,
            formatLatency,
            getLatencyBadgeClass,
            openDocs,
            // 环境管理导出
            environmentList,
            envDialogVisible,
            editingEnvId,
            envSubmitting,
            envSearchQuery,
            envForm,
            filteredEnvironments,
            openCreateEnvDialog,
            openEditEnvDialog,
            submitEnvForm,
            handleDeleteEnv,
            goToEnvTargets,
            goToEnvApis,
            goToEnvMachines,
            getEnvStatusBadgeClass,
            getEnvBorderTopColor,
            dashboardEnvironments,
            getEnvTargetCount,
            getEnvMachineCount,
            // 机器管理导出
            machineList,
            machineDialogVisible,
            editingMachineId,
            machineSubmitting,
            triggeringMachineId,
            machineSearchQuery,
            selectedMachineEnv,
            machineForm,
            onlineMachineCount,
            offlineMachineCount,
            avgTcpLatency,
            machineEnvTotalCount,
            machineEnvOnlineCount,
            machineEnvOfflineCount,
            machineEnvAvgTcpLatency,
            filteredMachines,
            openCreateMachineDialog,
            openEditMachineDialog,
            submitMachineForm,
            handleDeleteMachine,
            handleTriggerMachine,
            getMachineApiCount,
            goToMachineTargets,
            currentEnvMachines,
            // 接口管理导出
            apiList,
            apiDialogVisible,
            editingApiId,
            apiSubmitting,
            triggeringApiId,
            apiSearchQuery,
            selectedApiEnv,
            selectedApiMachine,
            selectedApiStatus,
            apiSampleJson,
            apiInferring,
            apiForm,
            healthyApiCount,
            issueApiCount,
            avgApiLatency,
            apiEnvTotalCount,
            apiEnvOnlineMachineCount,
            apiEnvHealthyCount,
            apiEnvIssueCount,
            apiEnvAvgLatency,
            currentEnvMachineOptions,
            filteredApis,
            openCreateApiDialog,
            openEditApiDialog,
            handleInferApiSchema,
            submitApiForm,
            handleDeleteApi,
            handleTriggerApi,
            openApiMetricsDrawer,
            // 接口列表批量操作
            selectedApiRows,
            apiTableRef,
            isBatchOperating,
            handleApiSelectionChange,
            clearApiSelection,
            handleBatchDeleteApis,
            handleBatchToggleActive,
            handleBatchSetInterval,
            apiCurrentPage,
            apiPageSize,
            paginatedApis,
            // Postman 风格工作台导出
            apiActiveTab,
            apiResponseTab,
            apiParamsList,
            apiHeadersList,
            apiBodyType,
            apiBodyText,
            apiAuthType,
            apiAuthConfig,
            apiTestRunning,
            apiTestResult,
            selectedMachineDisplayName,
            selectedMachineBaseUrl,
            selectedMachineHost,
            resetBaseUrlToMachine,
            onPathInput,
            addParamRow,
            removeParamRow,
            addHeaderRow,
            removeHeaderRow,
            systemDefaultHeaders,
            showDefaultHeaders,
            isHeaderOverridden,
            activeDefaultHeadersCount,
            getEffectiveHeaders,
            insertMacroToBody,
            formatBodyJson,
            minifyBodyJson,
            clearBodyJson,
            formatSchemaJson,
            formatSampleJson,
            copyResponseBody,
            formatIfJson,
            copyText,
            handleTestRunApi,
            inferSchemaFromTestResult,
            // 前置操作与后置操作导出
            apiPreActionsList,
            apiPostActionsList,
            addPreActionRow,
            removePreActionRow,
            applyPreActionPreset,
            addPostActionRow,
            removePostActionRow,
            applyPostActionPreset,
            onPostActionTypeChange,
            // 宿主机器运行环境与环境变量管理导出
            currentMachineEnvironment,
            envVarsDialogVisible,
            envVariablesList,
            envVariablesSaving,
            fetchMachineEnvironment,
            openEnvDialog,
            addEnvVarRow,
            removeEnvVarRow,
            saveEnvVariables,
            copyEnvVarRef,
            getVarRef,
            // Postman 数据导入导出
            postmanImportDialogVisible,
            postmanImportMachine,
            postmanImportMachineId,
            postmanImportLoading,
            postmanPreviewData,
            postmanSelectedApis,
            postmanSyncEnvVars,
            postmanUpdateBaseUrl,
            postmanConflictPolicy,
            postmanCronInterval,
            postmanRawJsonText,
            postmanImportActiveTab,
            postmanImportSuccessResult,
            openPostmanImportForMachine,
            openGenericPostmanImport,
            onPostmanImportMachineChange,
            handlePostmanFileChange,
            handlePostmanTextParse,
            toggleSelectAllPostmanApis,
            isPostmanApiSelected,
            togglePostmanApiSelection,
            executeConfirmPostmanImport,
            resetPostmanImport,
            goToImportedApisView,
            // 接口探针周期自定义与启停导出
            apiIntervalValue,
            apiIntervalUnit,
            setQuickInterval,
            formatIntervalDisplay,
            getIntervalTooltip,
            toggleApiActive,
            // 场景拨测域导出
            scenarioList,
            scenarioLoading,
            scenarioSearchQuery,
            selectedScenarioEnv,
            selectedScenarioMachine,
            selectedScenarioStatus,
            toggleScenarioActive,
            scenarioDialogVisible,
            editingScenarioId,
            scenarioSubmitting,
            scenarioForm,
            scenarioIntervalValue,
            scenarioIntervalUnit,
            setQuickScenarioInterval,
            scenarioSteps,
            activeStepIndex,
            activeStep,
            stepActiveTab,
            scenarioMachineOptions,
            scenarioMachineDisplayName,
            resetScenarioBaseUrlToMachine,
            filteredScenarios,
            scenarioTotalCount,
            scenarioActiveCount,
            scenarioCleanupCount,
            scenarioStepTotalCount,
            fetchScenarios,
            addScenarioStep,
            insertScenarioStep,
            moveScenarioStep,
            moveStepLeft,
            moveStepRight,
            cloneScenarioStep,
            removeScenarioStep,
            selectScenarioStep,
            scenarioSystemDefaultHeaders,
            showStepDefaultHeaders,
            activeScenarioDefaultHeadersCount,
            isStepHeaderOverridden,
            addStepParamRow,
            removeStepParamRow,
            addStepHeaderRow,
            removeStepHeaderRow,
            formatStepBodyJson,
            minifyStepBodyJson,
            clearStepBodyJson,
            onStepPathInput,
            addStepPreActionRow,
            removeStepPreActionRow,
            applyStepPreActionPreset,
            addStepPostActionRow,
            removeStepPostActionRow,
            onStepPostActionTypeChange,
            applyStepPostActionPreset,
            openCreateScenarioDialog,
            openEditScenarioDialog,
            submitScenarioForm,
            handleDeleteScenario,
            // 拨测执行引擎导出
            scenarioRunningId,
            scenarioResultVisible,
            scenarioResult,
            stepTestRunning,
            stepTestResult,
            handleRunScenario,
            getStepResultBadge,
            handleTestRunStep,
            // 节点 Schema 契约导出
            stepSchemaSampleJson,
            stepInferring,
            formatStepSchemaJson,
            inferStepSchemaFromSample,
            inferStepSchemaFromTestResult,
            safeFormatJson,
            // 从接口管理导入接口为链路节点
            apiImportDialogVisible,
            apiImportSearch,
            apiImportMethodFilter,
            apiImportSelection,
            apiImportTableRef,
            apiImportOrderedList,
            apiImportInsertPosition,
            moveImportedApiUp,
            moveImportedApiDown,
            removeImportedApi,
            clearAllImportedApis,
            importableApis,
            openApiImportDialog,
            handleApiImportSelectionChange,
            confirmImportApisAsSteps,
            fillActiveStepFromApi,
            getMethodBadgeStyle,
            getScenarioStatusBadgeClass,
            getScenarioStatusText,
            // 场景时序排障与历史流水
            scenarioMetricsDrawerVisible,
            scenarioMetricsLoading,
            activeScenarioMetrics,
            scenarioHistoryList,
            openScenarioMetricsDrawer,
            // 业务链路步骤折叠展开
            expandedScenarioStepIds,
            isScenarioStepsExpanded,
            toggleScenarioStepsExpand,
            isAllScenarioStepsExpanded,
            toggleAllScenarioStepsExpand,
            // 场景专属变量池 (隔离防污染)
            scenarioVariablesList,
            scenarioVariablesDrawerVisible,
            scenarioVariablesCount,
            addScenarioVariableRow,
            removeScenarioVariableRow,
            clearScenarioVariables,
            getScenarioVariablesObject,
            setScenarioVariablesFromObject,
            copyVariableMacro,
            stepResponseTab,
            stepExtractedVarNames,
            customExtractPath,
            customExtractVarName,
            customExtractPreview,
            stepExtractableFields,
            getStepResponseFormattedBody,
            isFieldExtractedInActiveStep,
            quickExtractFieldToScenarioVariable,
            addCustomExtractToScenarioVariable,
            insertScenarioVarToStepBody,
            insertScenarioVarToStepParam,
            insertScenarioVarToStepHeader,
            insertScenarioVarToStepPath,
            // 场景列表批量操作
            selectedScenarioRows,
            scenarioTableRef,
            isScenarioBatchOperating,
            handleScenarioSelectionChange,
            clearScenarioSelection,
            handleBatchDeleteScenarios,
            handleBatchToggleScenarioActive,
            handleBatchSetScenarioInterval,
            scenarioCurrentPage,
            scenarioPageSize,
            paginatedScenarios
        };

        // 调试与自动化测试全局挂载
        window.SchemaPulseApp = setupResult;

        return setupResult;
}
